function buildTrainingDatasetPayload(data) {
  return {
    labelOutcome: data.result === "draw" ? "draw" : data.result === "White" ? "white_wins" : "black_wins",
    labelColor: data.playerColor,
    labelOpening: data.opening,
    labelDifficulty: data.difficulty,
    snapshotBefore: data.ratingBefore,
    snapshotAfter: data.newRating,
    snapshotChange: data.ratingChange,
    outcome: data.result,
    strengths: data.analysisResult?.strengths || [],
    weaknesses: data.analysisResult?.weaknesses || [],
    coachRecommendations: data.analysisResult?.coachRecommendations || [],
    openingScore: data.analysisResult?.openingScore || 0,
    middleGameScore: data.analysisResult?.middleGameScore || 0,
    endgameScore: data.analysisResult?.endgameScore || 0,
    performanceScore: data.analysisResult?.performanceScore || 0,
    bestMoves: data.analysisResult?.bestMoves || 0,
    excellentMoves: data.analysisResult?.excellentMoves || 0,
    goodMoves: data.analysisResult?.goodMoves || 0,
    inaccuracies: data.analysisResult?.inaccuracies || 0,
    mistakes: data.analysisResult?.mistakes || 0,
    blunders: data.analysisResult?.blunders || 0,
    brilliantMoves: data.analysisResult?.brilliantMoves || 0,
    missedWins: data.analysisResult?.missedWins || 0,
    averageCentipawnLoss: data.analysisResult?.averageCentipawnLoss || 0,
    materialBalance: data.analysisResult?.materialBalance || 0,
    pieceActivityScore: data.analysisResult?.pieceActivityScore || 0,
    kingSafetyScore: data.analysisResult?.kingSafetyScore || 0,
    endgameQualityScore: data.analysisResult?.endgameQualityScore || 0,
    tacticalAbilityScore: data.analysisResult?.tacticalAbilityScore || 0,
    positionalPlayScore: data.analysisResult?.positionalPlayScore || 0,
    decisionMakingScore: data.analysisResult?.decisionMakingScore || 0,
    consistencyScore: data.analysisResult?.consistencyScore || 0,
    playingStyle: data.analysisResult?.playingStyle || "Balanced",
  };
}

module.exports = { buildTrainingDatasetPayload };